name: 'Deploy to Cloud Run'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: false
        default: 'v0.1.0'

env:
  PROJECT_ID: 'dicoding-submission-440805'
  REGION: 'asia-southeast2'
  SERVICE: 'bin-detective'
  DOCKER_IMAGE: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/bin-detective/bin-detective'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "${{ env.DOCKER_IMAGE }}:${{ github.event.inputs.version }}"
          flags: >-
            --cpu=2
            --memory=1024Mi
            --min-instances=0
            --max-instances=1
            --set-env-vars FIREBASE_STORAGE_BUCKET=dicoding-submission-440805.firebasestorage.app
            --set-env-vars IS_ON_DEV=false
            --set-env-vars FASTAPI_SERVICE=https://bin-detective-ml-476908432279.asia-southeast2.run.app
            --set-env-vars FASTAPI_PORT=7976
            --port=7070
          skip_default_labels: true

      # Step 4: Allow unauthenticated access to Cloud Run (if needed)
      - name: Allow unauthenticated access to Cloud Run
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE }} --region=${{ env.REGION }} --member=allUsers --role=roles/run.invoker

      # Step 5: Show output
      - name: Show output
        run: |
          echo "Deployment successful for version: ${{ github.event.inputs.version }}"
