# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Cloud Run Developer (roles/run.developer)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources
#
# 3. Change the values in the "env" block to match your values.

name: 'Build and Deploy to Cloud Run'

on:
  workflow_dispatch:  # This allows manual trigger

env:
  PROJECT_ID: 'dicoding-submission-440805' 
  REGION: 'asia-southeast2' 
  SERVICE: 'bin-detective-ml' 
  SERVICE_ACCOUNT: 'bindetective@dicoding-submission-440805.iam.gserviceaccount.com' # Service account for Cloud Run
  CALLER_SERVICE_ACCOUNT: 'bindetective@dicoding-submission-440805.iam.gserviceaccount.com'
  MODEL_ARCHIVE_PATH: 'https://www.kaggle.com/api/v1/models/bahiskaraananda/robin-efficientnetv2s/tensorFlow2/1.0-18m-ft144/1/download'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4


      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      # Authenticate to Google Cloud using the service account key
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0 # Authentication action
        with:
         credentials_json: '${{ secrets.GCP_SA_KEY }}' # Use the secret with the service account JSON key
         token_format: 'access_token'

      - name: 'Set up Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"  # Use your project ID
        
      # BEGIN - Docker auth and build
      #
      # If you already have a container image, you can omit these steps.
      # BEGIN - Docker auth and build
      - name: 'Docker Auth'
        uses: 'docker/login-action@v1'
        with:
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/bin-detective-grpc-service/bin-detective-service:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
          
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: 'asia-southeast2'
          image: 'asia-southeast2-docker.pkg.dev/dicoding-submission-440805/bin-detective-grpc-service/bin-detective-service:${{ github.sha }}'
          flags: >-
            --cpu=4
            --memory=2048Mi
            --min-instances=0
            --max-instances=1
            --set-env-vars MODEL_ARCHIVE_PATH=${{ env.MODEL_ARCHIVE_PATH }}
            --port=7976
      
      # Grant calling Cloud Run instance access
      - name: 'Grant invoker role to calling service'
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE }} --region=${{ env.REGION }} --member=serviceAccount:${{ env.CALLER_SERVICE_ACCOUNT }} --role=roles/run.invoker
      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |2-

          echo ${{ steps.deploy.outputs.url }}
