name: 'Release and Deploy to Cloud Run'

on:
  workflow_dispatch:  # This allows manual triggering of the workflow
    inputs:
      version:
        description: 'Version for the release (e.g., v0.1.1)'
        required: true
        default: 'v0.1.0'  # Default version, can be overridden when triggered

env:
  PROJECT_ID: 'dicoding-submission-440805'
  REGION: 'asia-southeast2'
  SERVICE: 'bin-detective'
  SERVICE_ACCOUNT: 'bindetective@dicoding-submission-440805.iam.gserviceaccount.com'  # Replace with the service account for Cloud Run
  FIREBASE_STORAGE_BUCKET_ENV: 'dicoding-submission-440805.firebasestorage.app'
  FASTAPI_SERVICE: 'https://bin-detective-ml-476908432279.asia-southeast2.run.app'
  FASTAPI_PORT: '7976'
  IS_ON_DEV: 'false'
  IS_CRON_JOB_SCHEDULED: 'false'
  VERSION: ${{ github.event.inputs.version }}  # Version passed when triggering the workflow

jobs:
  release_and_deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate to Google Cloud using the service account key
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0
        with:
         credentials_json: '${{ secrets.GCP_SA_KEY }}'
         token_format: 'access_token'

      - name: 'Set up Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"

      # Docker Auth and Build
      - name: 'Docker Auth'
        uses: 'docker/login-action@v1'
        with:
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/bin-detective/bin-detective:${{ env.VERSION }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'bin-detective'
          region: 'asia-southeast2'
          image: 'asia-southeast2-docker.pkg.dev/dicoding-submission-440805/bin-detective/bin-detective:${{ github.sha }}'
          flags: >-
            --cpu=2
            --memory=1024Mi
            --min-instances=0
            --max-instances=1
            --set-env-vars FIREBASE_STORAGE_BUCKET=dicoding-submission-440805.firebasestorage.app
            --set-env-vars IS_ON_DEV=false
            --set-env-vars FASTAPI_SERVICE=https://bin-detective-ml-476908432279.asia-southeast2.run.app
            --set-env-vars FASTAPI_PORT=7976
            --port=7070
          skip_default_labels: true

      - name: 'Create GitHub Release'
        run: |-
          echo "Creating GitHub release for version ${{ env.VERSION }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "${{ env.VERSION }}",
              "target_commitish": "main",
              "name": "${{ env.VERSION }}",
              "body": "Release for version ${{ env.VERSION }} of Bin Detective backend",
              "draft": false,
              "prerelease": false
            }' \
            "https://api.github.com/repos/${{ github.repository }}/releases"

      - name: 'Allow unauthenticated access'
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE }} --region=${{ env.REGION }} --member=allUsers --role=roles/run.invoker

      - name: 'Show output'
        run: |
          echo ${{ steps.deploy.outputs.url }}
